%%{init: {'theme':'default'}}%%
erDiagram
  compound {
    INTEGER compound_cid
    TEXT name
    DOUBLE molecular_weight
    TEXT molecular_formula
    DOUBLE polar_area
    DOUBLE complexity
    DOUBLE xlogp
    INTEGER heavy_atom_count
    INTEGER h_bond_donor_count
    INTEGER h_bond_acceptor_count
    INTEGER rotatable_bond_count
    TEXT inchi
    TEXT smiles
    TEXT inchi_key
    TEXT iupac_name
    DOUBLE exact_mass
    DOUBLE monoisotopic_mass
    INTEGER charge
    INTEGER covalent_unit_count
    INTEGER isotopic_atom_count
    INTEGER total_atom_stereo_count
    INTEGER defined_atom_stereo_count
    INTEGER undefined_atom_stereo_count
    INTEGER total_bond_stereo_count
    INTEGER defined_bond_stereo_count
    INTEGER undefined_bond_stereo_count
    INTEGER linked_pubchem_literature_count
    INTEGER linked_pubchem_patent_count
    INTEGER linked_pubchem_patent_family_count
    INTEGER annotation_type_count
    DATE create_date
    TEXT data_source
    TEXT data_source_category
    BOOLEAN tagged_by_pubchem
  }

  compound_synonym {
    INTEGER compound_cid
    TEXT synonym
  }

  compound_mesh_heading {
    INTEGER compound_cid
    TEXT mesh_heading
  }

  compound_bioassay {
    INTEGER compound_cid
    TEXT bioassay_id
  }

  compound ||--o{ compound_synonym : has
  compound ||--o{ compound_mesh_heading : has
  compound ||--o{ compound_bioassay : has